/* Autogenerated by png2wx.pl on Fri Jan 21 15:31:54 2011 */
#ifndef _TOOLBASVIEW_BITMAP_H_
#define _TOOLBASVIEW_BITMAP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void uninitialize_images(void);

extern wxBitmap *_img_mysql;
extern wxBitmap *_img_toolbasview;

#endif /* _TOOLBASVIEW_BITMAP_H_ */
