/* Autogenerated by png2wx.pl on Fri Mar 15 10:46:23 2013 */
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif
#include <wx/mstream.h>
#include "foldbar_bmp.h"

wxBitmap *_img_close;
wxBitmap *_img_minus;
wxBitmap *_img_plus;

void foldbar_initialize_images(void)
{
	{
		wxMemoryInputStream sm("\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\000\n\000\000\000\n\b\006\000\000\000\2152\317\275\000\000\000\031tEXtSoftware\000Adobe ImageReadyq\311e<\000\000\000\210IDATx\332l\216Q\n\200 \020D\327>\272A t\261\216\330\001\202n\320W\020\004\202\340\021\272A\020\266\023#\254\222\360\320]\237\3538\021Y\225^\231r\316\227\230\345\234\033t\233\225\033\365\251d\356\203\312\002pn\356dT\022\033A\361$\260\227>\207\257!G#\027\011\275\361s\314WV\256$\320\231\354\017\371\2579\255\315Te\246SI\221\021\332\314pd\377\313\324\310\a\032\013e_$#c\322\006\347\025`\000\036\302c\032Z\352d\360\000\000\000\000IEND\256B`\202", 230);
		_img_close = new wxBitmap(wxImage(sm));
	}
	{
		wxMemoryInputStream sm("\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\000\n\000\000\000\n\b\006\000\000\000\2152\317\275\000\000\000\031tEXtSoftware\000Adobe ImageReadyq\311e<\000\000\000.IDATx\332b\374\377\377?\0031\200\211\201H@}\205\014P7\356\0051q\340\275 50\023\177\3411\013,\3078\004|\r\020`\000\351\035\025mG&R\202\000\000\000\000IEND\256B`\202", 140);
		_img_minus = new wxBitmap(wxImage(sm));
	}
	{
		wxMemoryInputStream sm("\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\000\n\000\000\000\n\b\006\000\000\000\2152\317\275\000\000\000\031tEXtSoftware\000Adobe ImageReadyq\311e<\000\000\000GIDATx\332b\374\377\377?\0031\200\011]\200\221\221q/\bc\210\243\233\bT\004\026\000\2123\3425\021'\200\232\b\262\352?\016\274\027\244\006f\342/<f\375\242\215\033Y\260\210\355\300\246\220\221\330\000\a\b0\000M\027%\237\253\3127\373\000\000\000\000IEND\256B`\202", 165);
		_img_plus = new wxBitmap(wxImage(sm));
	}
	return;
}


void foldbar_clean_images(void){
    wxDELETE(_img_close);
    wxDELETE(_img_minus);
    wxDELETE(_img_plus);    
}
