/* Autogenerated by png2wx.pl on Fri Mar 15 10:46:23 2013 */
#ifndef _FOLDBAR_BMP_H_
#define _FOLDBAR_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void foldbar_initialize_images(void);
extern void foldbar_clean_images(void);


extern wxBitmap *_img_close;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;

#endif /* _FOLDBAR_BMP_H_ */
