name: Tests-Linux

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install wheel conan==1.*
          
          # gitlab support (wxwidgets, mysql, gdal)
          conan remote add gitlab https://gitlab.com/api/v4/packages/conan --force
          
          # create default profile with libstdc++11
          conan profile new default --detect --force
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update conf.tools.system.package_manager:mode=install default
          conan profile update conf.tools.system.package_manager:sudo=True default

      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-0 libgtk-3-dev
          sudo apt-get install libgnutls30 libgnutls28-dev
          sudo apt-get install libxcb-cursor0 libxcb-cursor-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev
          sudo apt-get install libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev
          sudo apt-get install libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-util-dev libxcb-render0-dev
          sudo apt-get install libxcb-dri2-0-dev libxcb-present-dev libxcb-glx0-dev libxcb-composite0-dev libxcb-xv0-dev
          sudo apt-get install libxcb-xvmc0-dev libxcb-xinput-dev libxcb-ewmh-dev libxcb-xf86dri0-dev libxcb-xrm-dev
          sudo apt-get install libxcb-record0-dev libxcb-xtest0-dev libxcb-res0-dev
          sudo apt-get install libx11-xcb-dev libx11-dev libfontenc-dev libxaw7-dev libxmu-dev libxmuu-dev libxpm-dev
          sudo apt-get install libxres-dev libxss-dev libxv-dev libxvmc-dev libxxf86vm-dev libxt-dev libxtst-dev
          sudo apt-get install libncurses5-dev libssl-dev  libice-dev
          sudo apt-get install libsm-dev libxau-dev libxcomposite-dev libxcursor-dev libxdamage-dev
          sudo apt-get install libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev
          sudo apt-get install libxkbfile-dev libxrandr-dev libxrender-dev
          sudo apt-get install xtrans-dev xkb-data uuid-dev libwebkit2gtk-4.1-dev

      - name: Install libraries
        run: |
          mkdir ${{github.workspace}}/bin
          cd ${{github.workspace}}/bin
          conan install .. -o unit_test=True --build=missing

      - name: Build
        run: |
          cd ${{github.workspace}}/bin
          conan build ..

      - name: Run unit testing
        working-directory: ${{github.workspace}}/bin/bin
        run: |
          ./UnitTests

